# Generated by Django 4.1.9 on 2023-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mycourses_recommended_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='recommended_courses',
            field=models.JSONField(default=list),
        ),
    ]
