# Generated by Django 4.1.9 on 2023-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='recommended_courses',
            field=models.JSONField(default=list),
        ),
    ]
