# Generated by Django 4.2.3 on 2023-07-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userpreference_recommended_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="topics",
            field=models.ManyToManyField(to="user.topic"),
        ),
    ]
