# Generated by Django 4.1.9 on 2023-07-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_job_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='topics',
        ),
        migrations.CreateModel(
            name='JobTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.job')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.topic')),
            ],
            options={
                'unique_together': {('job', 'topic')},
            },
        ),
    ]
